### ISSUE TITLE
Would it be possible to release 

### ISSUE THREAD

**Issue by warrensbox** [mmmorris1975/aws-key-rotator#3]
Would it be possible to rename the releases with the architecture?
```
aws-key-rotator-1.0.0-darwin
aws-key-rotator-1.0.0-linux
aws-key-rotator-1.0.0-windows.exe
```

To:
```
aws-key-rotator-1.0.0-darwin-amd64
aws-key-rotator-1.0.0-linux-amd64
aws-key-rotator-1.0.0-windows-amd64.exe
```

The reason I am asking is because it would be easier for users or programs to make an api call to `mmmorris1975/aws-key-rotator/releases` to get the correct
 binary that can be installed in their host machine. Would you have to create a new release to make this change?

**Comment by mmmorris1975** [comment]
added and released in v1.0.1
